FORMAT: 1A
HOST: https://api.tutorialinaja.tech/vidu

# Tutorialinaja - Video Uploader

DOCS Video Uploader Api

## API Host
* HOST: https://api.tutorialinaja.tech

##Api Version
* /vidu

## API Main End Point
* https://api.tutorialinaja.tech/vidu

## Health Check [/health-check]
___
**Table Routes:**
| URL             | Method | INFO                   |
| ----------------| ------ | -----------------------|
| `/health-check` | GET    | Check API status       |


### Health Check [GET /health-check]

+ Response 200 (application/json)

        {
            "code": 200,
            "response": "ok",
            "path": "/vidu/health-check",
            "method": "GET"
        }
                


## Video Upload [/v1/upload]
___
**Table Routes:**
| URL           | Method | INFO                                             |
| --------------| ------ | -------------------------------------------------|
| `/v1/upload`     | POST   | Upload Video File into media.tutorialinaja.tech  |

___
**Upload Videos Parameter:**
| Parameter    | type   | Status   | Description                   |
| ------------ | ------ | -------- | ----------------------------- |
| `file`       | binary | required | Binary file to be uploaded    |

### Upload Videos [POST /v1/upload]

+ Parameter
    + file (multipart/form-data; boundary=---BOUNDARY)

+ Response 200 (application/json)

        {
            "code": 200,
            "response": {
                "ETag": "\"4ea942dc1ad79e462a3e2926cb7f8b76\"",
                "Location": "https://s3.ap-southeast-1.amazonaws.com/media.tutorialinaja.tech/Project.mp4",
                "key": "Project.mp4",
                "Key": "Project.mp4",
                "Bucket": "media.tutorialinaja.tech"
            },
            "path": "/vidu/v1/upload",
            "method": "POST"
        }